In [1]:
[[12,34,56],[45,67,78],[12,56,78]]

[[12, 34, 56], [45, 67, 78], [12, 56, 78]]

In [3]:
import numpy

In [7]:
n = numpy.arange(27)

In [8]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [10]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
import cv2

In [13]:
img = cv2.imread("original.png",0)

In [14]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [15]:
img2 = cv2.imwrite("new_image.png",img)

In [16]:
img2

True

In [17]:
data = img[0:2,2:4]
data

array([[104, 121],
       [255, 255]], dtype=uint8)

In [18]:
for i in img:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [19]:
for i in img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [20]:
concat = numpy.hstack((img,img))
concat

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)